version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5500:5500"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tender_day
      - JWT_SECRET=yourStrongSecretHere
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
